apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer-agent
spec:
  template:
    spec:
      containers:
        - name: indexer-agent
          env:
            # Set this so it matches the index node pods
            - name: INDEXER_AGENT_INDEX_NODE_IDS
              value: index_node_0,index_node_1

            # Set this to your indexer's lat, long coordinates
            - name: INDEXER_AGENT_INDEXER_GEO_COORDINATES
              value: "0.00 0.00"

            # Set this to the public URL that your indexer serves from
            - name: INDEXER_AGENT_PUBLIC_INDEXER_URL
              value: http://not.localhost/
