apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: graph-node-image
    newName: graphprotocol/graph-node
    newTag: latest
  - name: graph-node-debug
    newName: graphprotocol/graph-node-debug
    newTag: latest
  - name: indexer-agent-image
    newName: ghcr.io/graphprotocol/indexer-agent
    newTag: latest
  - name: indexer-service-image
    newName: ghcr.io/graphprotocol/indexer-service
    newTag: latest
  - name: prometheus-image
    newName: prom/prometheus
    newTag: v2.23.0
  - name: busybox-image
    newName: busybox
    newTag: "1.30"
  - name: nginx-image
    newName: nginx
    newTag: latest
  - name: vector-node
    newName: connextproject/vector_node
    newTag: 0.2.1
patchesStrategicMerge:
  - ethereum_networks.yaml
  - index_node.yaml
  - query_node.yaml
  - indexer_agent.yaml
  - indexer_service.yaml
  - prometheus.yaml
