apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: graph-node-image
    newName: graphprotocol/graph-node
    newTag: v0.27.0
  - name: graph-node-debug
    newName: graphprotocol/graph-node-debug
    newTag: v0.27.0
  - name: indexer-agent-image
    newName: ghcr.io/graphprotocol/indexer-agent
    newTag: v0.20.4
  - name: indexer-service-image
    newName: ghcr.io/graphprotocol/indexer-service
    newTag: v0.20.4
  - name: prometheus-image
    newName: prom/prometheus
    newTag: v2.32.1
  - name: busybox-image
    newName: busybox
    newTag: "1.30"
  - name: nginx-image
    newName: nginx
    newTag: latest
  - name: gists/nfs-server
    newTag: 2.5.4
patchesStrategicMerge:
  - index_node.yaml
  - block_ingestor.yaml
  - query_node.yaml
  - indexer_agent.yaml
  - indexer_service.yaml
  - prometheus.yaml
