########################################################################
# Build image

FROM node:14-bullseye-slim as build

ENV NODE_ENV production

RUN apt-get update && apt-get install -y python build-essential git curl python3
ARG CI_JOB_TOKEN
RUN echo ${CI_JOB_TOKEN}

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh && sh /tmp/rustup.sh -y
ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /opt/indexer

# Copy root files
COPY .yarn/ .yarn/
COPY package.json .
COPY tsconfig.json .
COPY lerna.json .
COPY .yarnrc.yml .

# Copy shared and package files
COPY packages/indexer-common/ ./packages/indexer-common
COPY packages/indexer-agent/ ./packages/indexer-agent


# Install dependencies; include dev dependencies
RUN yarn install
RUN yarn compile

########################################################################
# Runtime image

FROM node:14-bullseye-slim

ENV NODE_ENV production
# When simulating large transactions, sometimes indexer-agent runs out of memory.
# This flag seems force node into GC earlier, preventing the crash
# 1536mb is 1.5GB, which is appropriate for an environment with 2GB RAM
ENV NODE_OPTIONS="--max-old-space-size=1536"
ARG CI_JOB_TOKEN
RUN echo ${CI_JOB_TOKEN}

RUN apt-get update && apt-get install -y python build-essential git curl

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh && sh /tmp/rustup.sh -y
ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /opt/indexer

# Copy root files
COPY .yarn/ .yarn/
COPY package.json .
COPY tsconfig.json .
COPY lerna.json .
COPY .yarnrc.yml .

# Copy build output
COPY --from=build /opt/indexer/packages/indexer-common/package.json /opt/indexer/packages/indexer-common/package.json
COPY --from=build /opt/indexer/packages/indexer-common/dist /opt/indexer/packages/indexer-common/dist
COPY --from=build /opt/indexer/packages/indexer-agent/package.json /opt/indexer/packages/indexer-agent/package.json
COPY --from=build /opt/indexer/packages/indexer-agent/dist /opt/indexer/packages/indexer-agent/dist

# Install dependencies; exclude dev dependencies
RUN yarn install
RUN yarn compile

ENV ETHEREUM ""

# Run the indexer-agent
WORKDIR /opt/indexer/packages/indexer-agent
ENTRYPOINT ["node", "dist/index.js", "start"]
