apiVersion: v1
kind: Service
metadata:
  name: index-node-block-ingestor
  labels:
    app: block-ingestor
    network: all
spec:
  selector:
    app: block-ingestor
    network: all
  ports:
  - name: json-rpc
    protocol: TCP
    port: 80
    targetPort: 8020
