apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: index-node-block-ingestor
spec:
  selector:
    matchLabels:
      app: block-ingestor
      network: all
  serviceName: index-node-block-ingestor
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: block-ingestor
        network: all
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8040"
    spec:
      nodeSelector:
        index: "1"
      tolerations:
        - key: "index"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: nfs-shared
          persistentVolumeClaim:
            claimName: nfs-shared
            readOnly: false
        - name: graph-node-config
          configMap:
            name: graph-node-config
      containers:
        - name: graph-node
          image: graph-node-image
          resources:
            requests:
              cpu: 600m
          ports:
            - name: http
              containerPort: 8000
            - name: json-rpc
              containerPort: 8020
            - name: metrics
              containerPort: 8040
          volumeMounts:
            - name: nfs-shared
              mountPath: /var/lib/graph
            - name: graph-node-config
              mountPath: /etc/graph-node
          env:
            - name: node_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRAPH_NODE_CONFIG
              value: /etc/graph-node/graph-node.toml
            - name: GRAPH_KILL_IF_UNRESPONSIVE
              value: "true"
            - name: GRAPH_LOG
              value: debug
            - name: postgres_host
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: postgres_user
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: postgres_pass
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: postgres_db
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: graph_db
            - name: ipfs
              value: https://ipfs.network.thegraph.com
            - name: GRAPH_ALLOW_NON_DETERMINISTIC_IPFS
              value: "true"
            - name: GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH
              value: "true"

            # Avoid some subgraphs fail with "Gas limit exceeded" error
            - name: GRAPH_MAX_GAS_PER_HANDLER
              value: "1_000_000_000_000_000"
            - name: GRAPH_ETHEREUM_REQUEST_RETRIES
              value: "30"
