apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: indexer-service-backend-config
spec:
  # Use a long timeout for WebSocket connections
  connectionDraining:
    drainingTimeoutSec: 0
