apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80":{}}}'
    beta.cloud.google.com/backend-config: '{"ports": {"80":"indexer-service-backend-config"}}'
spec:
  type: LoadBalancer
  selector:
    app: indexer-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7600
