apiVersion: v1
kind: Service
metadata:
  name: query-node
spec:
  type: NodePort
  selector:
    app: query-node
  ports:
    - name: http-nginx
      protocol: TCP
      port: 80
    - name: http
      port: 8000
    - name: ws
      port: 8001
    - name: index-node
      port: 8030
