name: Indexer Service Image

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/graphprotocol/indexer-service
          tag-sha: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up Node.js v20
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 20
      - name: Build and push Indexer Service image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.indexer-service
          # Enabling the line below restricts Docker images to only be built for branches
          # push: ${{github.event_name != 'pull_request'}}
          push: true
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
          build-args: NPM_TOKEN=${{secrets.graphprotocol_npm_token}}
