name: osv-scanner

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run OSV scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.8
        with:
          scan-args: |-
            --lockfile=yarn.lock
